# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required ReadTheDocs version
version: 2

# Set the OS, version of Python and other tools
build:
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"  # Use Python 3.13 for documentation build
  jobs:
    pre_build:
      # Commands to run before building the docs
      - pip install -e ".[docs]"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false  # Set to false initially to avoid build failures

# Python dependencies required to build the docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Build documentation in additional formats such as PDF and ePub
formats:
  - pdf
  - epub
