# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"  # Use Python 3.9 for documentation build
  jobs:
    pre_build:
      # Run this command before building the docs to ensure we have the latest dependencies
      - pip install -e ".[docs]"
      - python -c "import sys; sys.path.insert(0, '.')"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true  # Treat warnings as errors to ensure high-quality docs

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
  system_packages: true

# Build documentation in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Don't use submodules for documentation (we're not using Git submodules)
submodules:
  include: all
  recursive: true